edition = "2021"
hard_tabs = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
trailing_comma = "Never"
use_field_init_shorthand = true
unstable_features = true
match_block_trailing_comma = true